// <auto-generated />
using System;
using LicenseManager.Licenses.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LicenseManager.Licenses.Migrations
{
    [DbContext(typeof(LicensesDbContext))]
    partial class LicensesDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LicenseManager.Licenses.Domain.Aggregates.Assignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastInvokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("LicenseId")
                        .HasColumnType("uuid");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("LicenseId");

                    b.HasIndex("UserId");

                    b.ToTable("Assignments");
                });

            modelBuilder.Entity("LicenseManager.Licenses.Domain.Aggregates.License", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DepartmentId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsCancelled")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsPaymentValid")
                        .HasColumnType("boolean");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("UsageCount")
                        .HasColumnType("integer");

                    b.Property<string>("Vendor")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("Licenses");
                });

            modelBuilder.Entity("LicenseManager.Licenses.Domain.Aggregates.Assignment", b =>
                {
                    b.HasOne("LicenseManager.Licenses.Domain.Aggregates.License", null)
                        .WithMany("Assignments")
                        .HasForeignKey("LicenseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LicenseManager.Licenses.Domain.Aggregates.License", b =>
                {
                    b.OwnsOne("LicenseManager.Licenses.Domain.ValueObjects.LicenseTerms", "Terms", b1 =>
                        {
                            b1.Property<Guid>("LicenseId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime?>("ExpirationDate")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("Terms_ExpirationDate");

                            b1.Property<bool>("IsRenewable")
                                .HasColumnType("boolean")
                                .HasColumnName("Terms_IsRenewable");

                            b1.Property<int?>("MaxUsers")
                                .HasColumnType("integer")
                                .HasColumnName("Terms_MaxUsers");

                            b1.Property<int>("Mode")
                                .HasColumnType("integer")
                                .HasColumnName("Terms_Mode");

                            b1.Property<DateTime?>("RenewalDate")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("Terms_RenewalDate");

                            b1.Property<int>("Type")
                                .HasColumnType("integer")
                                .HasColumnName("Terms_Type");

                            b1.Property<int?>("UsageLimit")
                                .HasColumnType("integer")
                                .HasColumnName("Terms_UsageLimit");

                            b1.HasKey("LicenseId");

                            b1.ToTable("Licenses");

                            b1.WithOwner()
                                .HasForeignKey("LicenseId");
                        });

                    b.Navigation("Terms")
                        .IsRequired();
                });

            modelBuilder.Entity("LicenseManager.Licenses.Domain.Aggregates.License", b =>
                {
                    b.Navigation("Assignments");
                });
#pragma warning restore 612, 618
        }
    }
}
